# Generated by Django 3.2.7 on 2023-06-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPlanets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(max_length=100)),
                ('chemical_elements', models.CharField(max_length=999)),
                ('water_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance', models.FloatField()),
                ('probability', models.CharField(choices=[('UC', 'uncertain'), ('L', 'likely'), ('UL', 'unlikely')], max_length=255)),
            ],
        ),
    ]
